### PR TITLE
fixes for Custom Components

### PR DESCRIPTION
**Pull request by strubelz**
So I created a plugin which can load components from jar or class files, but it needs these two methods to work. Maybe other people want to use this plugin too.

### CODE REVIEW

**Comment by kotcrab** [comment]
Thanks for your contribution, please address the comments I made in the review. Also feel free to add yourself to `CONTRIBUTORS` file.

**Comment by strubelz** [comment]
I sorry, but I don't see any reviews?

**Comment by kotcrab** [comment]
@strubelz oops sorry I didn't submit it.

**Comment by kotcrab** [comment]
Thanks!

**Pull request merged**
